# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(664, 548)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.list_notes = QtWidgets.QListWidget(self.centralwidget)
        self.list_notes.setGeometry(QtCore.QRect(340, 40, 251, 111))
        self.list_notes.setObjectName("list_notes")
        self.list_tags = QtWidgets.QListWidget(self.centralwidget)
        self.list_tags.setGeometry(QtCore.QRect(340, 250, 261, 121))
        self.list_tags.setObjectName("list_tags")
        self.field_tag = QtWidgets.QLabel(self.centralwidget)
        self.field_tag.setGeometry(QtCore.QRect(340, 380, 261, 20))
        self.field_tag.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border: 2px solid #8c8c8c; /* Gray */")
        self.field_tag.setObjectName("field_tag")
        self.list_tags_label = QtWidgets.QLabel(self.centralwidget)
        self.list_tags_label.setGeometry(QtCore.QRect(340, 230, 141, 21))
        self.list_tags_label.setObjectName("list_tags_label")
        self.button_note_create = QtWidgets.QPushButton(self.centralwidget)
        self.button_note_create.setGeometry(QtCore.QRect(340, 160, 121, 28))
        self.button_note_create.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border: 2px solid #000000; /* Gray */")
        self.button_note_create.setObjectName("button_note_create")
        self.butto_note_del = QtWidgets.QPushButton(self.centralwidget)
        self.butto_note_del.setGeometry(QtCore.QRect(470, 160, 121, 28))
        self.butto_note_del.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border: 2px solid #000000; /* Gray */")
        self.butto_note_del.setObjectName("butto_note_del")
        self.button_note_save = QtWidgets.QPushButton(self.centralwidget)
        self.button_note_save.setGeometry(QtCore.QRect(340, 190, 251, 28))
        self.button_note_save.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border: 2px solid #000000; /* Gray */")
        self.button_note_save.setObjectName("button_note_save")
        self.button_tag_add = QtWidgets.QPushButton(self.centralwidget)
        self.button_tag_add.setGeometry(QtCore.QRect(340, 410, 121, 31))
        self.button_tag_add.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border: 2px solid #000000; /* Gray */")
        self.button_tag_add.setObjectName("button_tag_add")
        self.button_tag_del = QtWidgets.QPushButton(self.centralwidget)
        self.button_tag_del.setGeometry(QtCore.QRect(460, 410, 141, 31))
        self.button_tag_del.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border: 2px solid #000000; /* Gray */")
        self.button_tag_del.setObjectName("button_tag_del")
        self.button_tag_seach = QtWidgets.QPushButton(self.centralwidget)
        self.button_tag_seach.setGeometry(QtCore.QRect(340, 450, 261, 28))
        self.button_tag_seach.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border: 2px solid #000000; /* Gray */")
        self.button_tag_seach.setObjectName("button_tag_seach")
        self.list_notes_label = QtWidgets.QLabel(self.centralwidget)
        self.list_notes_label.setGeometry(QtCore.QRect(340, 20, 141, 21))
        self.list_notes_label.setObjectName("list_notes_label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(40, 30, 291, 451))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 664, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.field_tag.setText(_translate("MainWindow", "Введіть тег..."))
        self.list_tags_label.setText(_translate("MainWindow", "Список тегів"))
        self.button_note_create.setText(_translate("MainWindow", "Створити замітку"))
        self.butto_note_del.setText(_translate("MainWindow", "Видалити замітку"))
        self.button_note_save.setText(_translate("MainWindow", "Зберегти замітку"))
        self.button_tag_add.setText(_translate("MainWindow", "Додати до замітки"))
        self.button_tag_del.setText(_translate("MainWindow", "Відкріпити від замітки"))
        self.button_tag_seach.setText(_translate("MainWindow", "Шукати замітки по тегу"))
        self.list_notes_label.setText(_translate("MainWindow", "Список заміток"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
